package Acme::CPANLists::Import::PerlAdvent::2015_12_09;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2015/2015-12-09.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Mojo::DOM"},{module=>"Mojo::UserAgent"},{module=>"Web::Query"}],summary=>"Modules mentioned in Perl Advent Calendar 2015 (day 09)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2015 (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2015/2015-12-09.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

