package Acme::CPANLists::Import::PerlAdvent::2015;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2015/] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"GeoIP2::Database::Reader"},{module=>"App::cpanminus"},{module=>"App::cpm"},{module=>"Menlo"},{module=>"Devel::CheckLib"},{module=>"FFI::CheckLib"},{module=>"FFI::Platypus"},{module=>"FFI::Platypus::Type::StringArray"},{module=>"FFI::Raw"},{module=>"Devel::Hide"},{module=>"Lingua::EN::Inflexion"},{module=>"Convert::CookingTimes"},{module=>"Text::Hogan"},{module=>"Text::Hogan::Compiler"},{module=>"Reply"},{module=>"Reply::Plugin"},{module=>"Reply::Plugin::AutoRefresh"},{module=>"Reply::Plugin::CarpReply"},{module=>"Reply::Plugin::CollapseStack"},{module=>"Reply::Plugin::Editor"},{module=>"Mojo::DOM"},{module=>"Mojo::UserAgent"},{module=>"Web::Query"},{module=>"MetaCPAN::Client"},{module=>"Module::CPANfile"},{module=>"WWW::Mechanize::Cached"},{module=>"Smart::Comments"},{module=>"Config::Station"},{module=>"DBI"},{module=>"DBIx::Class"},{module=>"IO::All"},{module=>"JSONY"},{module=>"Moo"},{module=>"JSON::Path"},{module=>"File::Serialize"},{module=>"Moose"},{module=>"Stepford"},{module=>"Stepford::Role::Step"},{module=>"Stepford::Role::Step::FileGenerator"},{module=>"Stepford::Role::Step::FileGenerator::Atomic"},{module=>"Stepford::Runner"},{module=>"File::stat"},{module=>"POSIX"},{module=>"Process::Status"},{module=>"Sort::ByExample"},{module=>"CHI"},{module=>"CHI::Driver::Redis"},{module=>"Cache::Cache"},{module=>"Cache::Redis"},{module=>"Redis"},{module=>"Redis::Fast"},{module=>"Redis::LeaderBoard"},{module=>"Redis::Namespace"},{module=>"feature"},{module=>"AnsibleModule"},{module=>"Mojo::IOLoop"},{module=>"Regexp::Common"},{module=>"Device::Chip"},{module=>"Device::Chip::Adapter"},{module=>"Future"}],summary=>"Modules mentioned in Perl Advent Calendar 2015"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2015

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2015/> (retrieved on 2016-11-06). Visit the URL for the full contents.

