package Acme::CPANLists::Import::PerlAdvent::2015_12_03;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2015/2015-12-03.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Devel::CheckLib"},{module=>"FFI::CheckLib"},{module=>"FFI::Platypus"},{module=>"FFI::Platypus::Type::StringArray"},{module=>"FFI::Raw"}],summary=>"Modules mentioned in Perl Advent Calendar 2015 (day 03)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2015 (day 03)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2015/2015-12-03.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

