package Acme::CPANLists::Import::PerlAdvent::2015_12_20;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2015/2015-12-20.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"CHI"},{module=>"CHI::Driver::Redis"},{module=>"Cache::Cache"},{module=>"Cache::Redis"},{module=>"Redis"},{module=>"Redis::Fast"},{module=>"Redis::LeaderBoard"},{module=>"Redis::Namespace"}],summary=>"Modules mentioned in Perl Advent Calendar 2015 (day 20)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2015 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2015/2015-12-20.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

