package Acme::CPANLists::Import::PerlAdvent::2015_12_18;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2015/2015-12-18.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Sereal"}],summary=>"Modules mentioned in Perl Advent Calendar 2015 (day 18)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2015 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2015/2015-12-18.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

