package Acme::CPANLists::Import::PerlAdvent::2015_12_24;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2015/2015-12-24.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Device::Chip"},{module=>"Device::Chip::Adapter"},{module=>"Future"}],summary=>"Modules mentioned in Perl Advent Calendar 2015 (day 24)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2015 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2015/2015-12-24.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

